"""Add payment fields

Revision ID: 5d76dd7f3c9a
Revises: e611e6a531ea
Create Date: 2025-01-30 16:14:27.220445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d76dd7f3c9a'
down_revision = 'e611e6a531ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_confirmed')

    # ### end Alembic commands ###
